export const documents = [
  {
    id: 1,
    title: "Building Safety Certificate",
    category: "Certificates",
    description: "Statutory record confirming school building safety compliance.",
    pdf: "#",
  },
  {
    id: 2,
    title: "Fire Safety",
    category: "Certificates",
    description: "Official fire safety approval and related compliance details.",
    pdf: "#",
  },
  {
    id: 3,
    title: "Water & Health Sanitation",
    category: "Certificates",
    description: "Health, sanitation, and water safety documentation for the campus.",
    pdf: "#",
  },
  {
    id: 4,
    title: "No Objection Certificate",
    category: "Certificates",
    description: "Mandatory school NOC issued by the relevant authority.",
    pdf: "#",
  },
  {
    id: 5,
    title: "Recognition",
    category: "Certificates",
    description: "Official recognition records for school operations and compliance.",
    pdf: "#",
  },
  {
    id: 6,
    title: "Trust Deed",
    category: "Administration",
    description: "Core governing trust document related to school administration.",
    pdf: "#",
  },
  {
    id: 7,
    title: "SMC",
    category: "Administration",
    description: "School Management Committee details and required governance records.",
    pdf: "#",
  },
  {
    id: 8,
    title: "DEO",
    category: "Administration",
    description: "Administrative document pertaining to district education records.",
    pdf: "#",
  },
  {
    id: 9,
    title: "PTA",
    category: "Administration",
    description: "Parent Teacher Association details and supporting information.",
    pdf: "#",
  },
  {
    id: 10,
    title: "Fee Structure",
    category: "Fee Structure",
    description: "Published fee structure and related disclosure information.",
    pdf: "#",
  },
  {
    id: 11,
    title: "Academic Calendar",
    category: "Academics",
    description: "School academic schedule including key terms and milestones.",
    pdf: "#",
  },
  {
    id: 12,
    title: "Projected Schedule",
    category: "Academics",
    description: "Projected academic planning schedule for the school year.",
    pdf: "#",
  },
  {
    id: 13,
    title: "Projected Event (Pre-school)",
    category: "Events",
    description: "Planned events and activity schedule for pre-school students.",
    pdf: "#",
  },
  {
    id: 14,
    title: "Projected Event (Adrian Junior)",
    category: "Events",
    description: "Planned events and student engagement calendar for Adrian Junior.",
    pdf: "#",
  },
  {
    id: 15,
    title: "Projected Event (Adrian Loyal Senior)",
    category: "Events",
    description: "Projected events and annual planning for Adrian Loyal Senior.",
    pdf: "#",
  },
];
